# @name getToken
POST https://www.reddit.com/api/v1/access_token
User-Agent: {{user_agent}}
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{client_id}}:{{client_secret}}

grant_type=password
&username={{username}}
&password={{password}}

###

@baseUrl = https://oauth.reddit.com

@subreddit = aPRAWTest
@submissionId = h7mna9
@commentId = fuoew5r

# @name getSubreddit
GET {{baseUrl}}/r/{{subreddit}}/about
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getNonexistentSubreddit
GET {{baseUrl}}/r/asjdfkljaskldf/about
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getComment
GET {{baseUrl}}/api/info?id=t1_{{commentId}}
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getReplies
GET {{baseUrl}}/r/{{subreddit}}/comments/{{submissionId}}/_/{{commentId}}
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getUser
GET {{baseUrl}}/api/v1/me
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getKarma
GET {{baseUrl}}/api/v1/me/karma
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getInbox
GET {{baseUrl}}/message/inbox
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getRandomSubmission
GET {{baseUrl}}/r/memes/random
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getSubredditRemovalReasons
GET {{baseUrl}}/api/v1/{{subreddit}}/removal_reasons
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getSubredditRemovalReason
DELETE {{baseUrl}}/api/v1/{{subreddit}}/removal_reasons/15bdq4obounrr
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getSubredditSettings
GET {{baseUrl}}/r/{{subreddit}}/about/edit
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

@conversationId = eqjy3

# @name getModmailConversation
GET {{baseUrl}}/api/mod/conversations/{{conversationId}}
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}
