# @name getToken
POST https://www.reddit.com/api/v1/access_token
User-Agent: {{user_agent}}
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{client_id}}:{{client_secret}}

grant_type=password&username={{username}}&password={{password}}

###

@baseUrl = https://oauth.reddit.com

@commentId = fuoew5r

# @name getComment
GET {{baseUrl}}/api/info?id=t1_{{commentId}}
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getReplies
GET {{baseUrl}}/r/facepalm/comments/h9rukl/_/fuyjkrm
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getUser
GET {{baseUrl}}/api/v1/me
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getKarma
GET {{baseUrl}}/api/v1/me/karma
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}
