# @name getToken
POST https://www.reddit.com/api/v1/access_token
User-Agent: {{user_agent}}
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{client_id}}:{{client_secret}}

grant_type=password&username={{username}}&password={{password}}

###

@baseUrl = https://oauth.reddit.com

@subreddit = aPRAWTest
@wikiPage = index

###

# @name getWiki
GET {{baseUrl}}/r/{{subreddit}}/wiki/pages
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getWikiRevisions
GET {{baseUrl}}/r/{{subreddit}}/wiki/revisions
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}

###

# @name getWikiPage
GET {{baseUrl}}/r/{{subreddit}}/wiki/{{wikiPage}}
User-Agent: {{user_agent}}
Content-Type: application/json
Authorization: {{getToken.response.body.token_type}} {{getToken.response.body.access_token}}
